### ISSUE TITLE
Wiki revision preview does not work

### ISSUE THREAD

**Issue by frederni** [Nabla-NTNU/nablaweb#563] opened 2021-12-12 22:24 UTC
Trying to preview changes on the wiki only results in empty website template. The height and width seems off as well. See image below

![image](https://user-images.githubusercontent.com/23258333/145731877-b258cf1c-c55f-4220-8245-71618318ea39.png)

**Comment by alexarntzen** [comment] 2022-01-31 15:29
duplicate of #397

**Comment by alexarntzen** [comment] 2022-01-31 15:31
Duplicate of #397

**Closed** 2022-02-25 18:51 UTC
Labels: bug, minor, Wiki
